name: bunny_love_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  video_player: ^2.8.2
  audioplayers: ^5.2.1
  flutter_animate: ^4.5.0

dev_dependencies:
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/audio/
    - assets/images/
    - web/bunny_forest.html

  fonts:
    - family: Bokutoh
      fonts:
        - asset: assets/fonts/FOT-RodinBokutoh Pro EB.otf


flutter_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png

flutter_native_splash:
  color: "#000000"          # or a color that matches your video
  image: assets/images/icon.png   # optional small image shown on native splash
  android: true
  ios: true
  android_disable_fullscreen: true
